server:
  port: 8080
spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      mvc:
        routes:
          - id: VEHICLE-SERVICE
            uri:  lb://VEHICLE-SERVICE
            predicates:
              - Path=/vehicle/**

eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true

